"""add user_id to order

Revision ID: 35e989fec2b4
Revises: 42231a396807
Create Date: 2025-11-16 14:20:34.574348

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35e989fec2b4"
down_revision: str | Sequence[str] | None = "42231a396807"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "user_id")
    op.add_column(
        "orders", sa.Column("user_id", sa.BigInteger(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "user_id")
    op.add_column(
        "order_items",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
